name: Deploy to AWS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Create deployment package
      run: |
        VERSION=$(date +%Y%m%d_%H%M%S)
        zip -r deploy_${VERSION}.zip * -x "node_modules/*"

    - name: Upload to S3
      run: |
        aws s3 cp deploy_${VERSION}.zip s3://billzzy-deployments/releases/deploy_${VERSION}.zip

    - name: Deploy from S3
      run: |
        aws deploy create-deployment \
          --application-name billzzy-app \
          --deployment-group-name billzzy-deployment-group \
          --s3-location bucket=billzzy-deployments,key=releases/deploy_${VERSION}.zip,bundleType=zip